# Module 3 - NumPy Random Module

## 1. Random Numbers

### Definition

Random numbers are numbers generated without following a fixed sequence.

NumPy provides random functions to generate different types of random data.

### Real-world Example

Random numbers can be used to simulate the results of rolling a dice.

### Business Example

Businesses can use random data for simulations and testing.

### AI/ML Example

Random numbers are used to create sample data and initialize values in Machine Learning models.

In [1]:
import numpy as np

numbers = np.random.rand(5)

print(numbers)

[0.25915447 0.91501369 0.83317614 0.80313349 0.05144571]


### Explanation

The `np.random.rand(5)` function generates five random numbers between 0 and 1.

Each value is a floating-point number.

### Best Practices

Use random functions when you need randomly generated numerical data.

### Common Mistakes

Assuming that random values will always be the same every time the code runs.

## 2. Random Seed

### Definition

A random seed is used to make random results repeatable.

When we use the same seed, NumPy generates the same random values each time.

### Real-world Example

A seed is like using the same starting point in a random experiment so that we can reproduce the same result.

### Business Example

A business can use a fixed seed when testing simulations so that the same test data can be reproduced.

### AI/ML Example

Random seeds are commonly used in Machine Learning experiments to make results reproducible.


In [2]:
np.random.seed(10)

numbers = np.random.rand(5)

print(numbers)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


### Explanation

The `np.random.seed(10)` function sets a fixed starting point for random number generation.

Running the code again with the same seed produces the same values.

### Best Practices

Use a fixed seed when you need reproducible results during testing or experiments.

### Common Mistakes

Changing the seed and expecting the same random output.

## 3. Random Integers

### Definition

Random integers are whole numbers generated randomly within a given range.

NumPy provides `np.random.randint()` to generate random integer values.

### Real-world Example

Random integers can be used to simulate dice rolls.

### Business Example

A company can use random integers to create sample data for testing.

### AI/ML Example

Random integers can be used to generate sample datasets and test Machine Learning programs.

In [3]:
numbers = np.random.randint(1, 10, 5)

print(numbers)

[1 2 9 1 9]


### Explanation

The `np.random.randint(1, 10, 5)` function generates 5 random integers from 1 to 9.

The upper limit 10 is not included.

### Best Practices

Clearly define the minimum, maximum, and number of values required.

### Common Mistakes

Forgetting that the upper limit in `randint()` is excluded.

## 4. Random Choice

### Definition

Random Choice selects random values from a given array.

It is useful when we need to randomly select one or more items from a dataset.

### Real-world Example

A teacher can randomly select students for a classroom activity.

### Business Example

A company can randomly select customers for a survey.

### AI/ML Example

Random choice can be used for creating random samples from a dataset.

In [7]:
students = np.array(["A", "B", "C", "D", "E"])

selected = np.random.choice(students, 2)

print(selected)

['D' 'A']


###  Explanation

The `np.random.choice()` function randomly selects 2 students from the `students` array.

The selected values may change each time the code runs.

### Best Practices

Use `np.random.choice()` when you need to randomly select values from an existing array.

### Common Mistakes

Selecting more values than available when using sampling without replacement.

## 5. Shuffle

### Definition

Shuffle randomly changes the order of elements in an array.

It modifies the original array directly.

### Real-world Example

A teacher can shuffle a list of students before assigning them to groups.

### Business Example

A company can shuffle customer records before creating random test samples.

### AI/ML Example

Shuffling data is useful before training a Machine Learning model to avoid unwanted ordering in the dataset.

In [8]:
students = np.array(["A", "B", "C", "D", "E"])

np.random.shuffle(students)

print(students)

['A' 'B' 'E' 'C' 'D']


###  Explanation

The `np.random.shuffle()` function randomly changes the order of the elements.

The original `students` array is changed directly.

### Best Practices

Use `shuffle()` when you want to randomly rearrange the existing array.

### Common Mistakes

Forgetting that `shuffle()` modifies the original array.

## 6. Permutation

### Definition

Permutation returns a randomly rearranged copy of an array.

Unlike `shuffle()`, it does not change the original array.

### Real-world Example

A teacher can create a random order of students while keeping the original student list unchanged.

### Business Example

A company can create a random order of customer records for testing without modifying the original data.

### AI/ML Example

Permutation can be used to create randomized versions of data for testing and analysis.

In [9]:
students = np.array(["A", "B", "C", "D", "E"])

random_students = np.random.permutation(students)

print("Original:", students)
print("Permutation:", random_students)

Original: ['A' 'B' 'C' 'D' 'E']
Permutation: ['D' 'B' 'C' 'E' 'A']


### Explanation

The `np.random.permutation()` function creates a randomly rearranged copy of the array.

The original `students` array remains unchanged.

### Best Practices

Use `permutation()` when you need a randomized copy while keeping the original data unchanged.

### Common Mistakes

Confusing `permutation()` with `shuffle()`. `shuffle()` changes the original array, while `permutation()` returns a new randomized array.

## 7. Random Distributions

### Definition

A random distribution describes how randomly generated values are spread across a range.

NumPy provides different distributions for generating random data based on specific patterns.

### Real-world Example

A normal distribution can be used to represent measurements such as student marks, where most values are close to the average.

### Business Example

Businesses can use random distributions to create sample data and perform simulations.

### AI/ML Example

Random distributions are used to generate sample data and test Machine Learning models.


In [10]:
data = np.random.normal(50, 10, 5)

print(data)

[52.2863013  54.45137613 38.63397788 51.35136878 64.84537002]


###  Explanation

`np.random.normal()` generates random values using a normal distribution.

Here, `50` is the mean, `10` is the standard deviation, and `5` is the number of values generated.

### Best Practices

Choose the appropriate random distribution based on the type of data you want to simulate.

### Common Mistakes

Confusing the mean and standard deviation parameters when generating a distribution.

## Advantages

- Easy to generate random data.
- Useful for simulations and testing.
- Supports different random distributions.
- Helps create sample datasets.
- Useful in AI/ML experiments.

## Limitations

- Random results can change each time.
- Some experiments require a fixed seed for reproducibility.
- Choosing an incorrect distribution can produce unsuitable data.
- Random data may not always represent real-world data accurately.

## Interview Questions and Answers

### 1. What is the NumPy Random module?

It is a module used to generate random numbers and random data.

### 2. Why is a random seed used?

A random seed is used to make random results reproducible.

### 3. What does np.random.randint() do?

It generates random integer values within a specified range.

### 4. What does np.random.choice() do?

It randomly selects values from a given array.

### 5. What is the difference between shuffle() and permutation()?

`shuffle()` changes the original array, while permutation() returns a randomly rearranged copy.

### 6. What does np.random.rand() generate?

It generates random floating-point values between 0 and 1.

### 7. What is a random distribution?

A random distribution describes how randomly generated values are spread across a range.

### 8. What is a normal distribution?

A normal distribution is a distribution where values are generally concentrated around the mean.

### 9. Where are random numbers used in AI/ML?

They are used for sample data generation, testing, simulations, and Machine Learning experiments.

### 10. Why is reproducibility important in Machine Learning?

Reproducibility helps us get the same results when an experiment is repeated using the same conditions.

## Self Reflection

I learned how to generate different types of random data using NumPy.

I practiced random numbers, random integers, random choice, shuffle, and permutation.

I also understood how random distributions and random seeds are useful in AI/ML experiments.